FROM alpine:3.17

ARG TARGETARCH
ARG TARGETPLATFORM
ARG BUILDPLATFORM

ARG HELM_VERSION=3.7.0
ARG HELMFILE_VERSION=0.146.0
ARG KUBECTL_VERSION=1.22.16
ARG KUSTOMIZE_VERSION=4.5.6


# COMMON
RUN apk add --update --no-cache curl ca-certificates

# HELM
ENV HELM_BASE_URL="https://get.helm.sh"
ENV TAR_FILE="helm-v${HELM_VERSION}-linux-${TARGETARCH}.tar.gz"
RUN curl -sL ${HELM_BASE_URL}/${TAR_FILE} | tar -xvz && \
    mv linux-${TARGETARCH}/helm /usr/bin/helm && \
    chmod +x /usr/bin/helm && \
    rm -rf linux-${TARGETARCH} && \
    helm repo add "stable" "https://charts.helm.sh/stable" --force-update

# HELMFILE
RUN curl -sL https://github.com/helmfile/helmfile/releases/download/v${HELMFILE_VERSION}/helmfile_${HELMFILE_VERSION}_linux_${TARGETARCH}.tar.gz -o - | tar xz -C /usr/bin/ && \
    chmod +x /usr/bin/helmfile

# KUBECTL
RUN curl -sLO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_VERSION}/bin/linux/${TARGETARCH}/kubectl && \
    mv kubectl /usr/bin/kubectl && \
    chmod +x /usr/bin/kubectl

# KUSTOMIZE
RUN curl -sLO https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv${KUSTOMIZE_VERSION}/kustomize_v${KUSTOMIZE_VERSION}_linux_${TARGETARCH}.tar.gz && \
    tar xvzf kustomize_v${KUSTOMIZE_VERSION}_linux_${TARGETARCH}.tar.gz && \
    mv kustomize /usr/bin/kustomize && \
    chmod +x /usr/bin/kustomize && \
    rm -rf kustomize_v${KUSTOMIZE_VERSION}_linux_${TARGETARCH}.tar.gz


WORKDIR /app
